export const FETCH_EVENT_GEOINFO_STARTED = 'FETCH_EVENT_GEOINFO_STARTED';
export const FETCH_EVENT_GEOINFO_FAILURE = 'FETCH_EVENT_GEOINFO_FAILURE ';
export const FETCH_EVENT_GEOINFO_SUCCESS = 'FETCH_EVENT_GEOINFO_SUCCESS';

export const UPDATE_SELECTED_INDEX = 'UPDATE_SELECTED_INDEX';

export const FETCH_USER_INFO_STARTED = 'FETCH_USER_INFO_STARTED';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_BATCH_STARTED = 'FETCH_USER_BATCH_STARTED';
export const FETCH_USER_BATCH_FAILURE = 'FETCH_USER_BATCH_FAILURE';
export const FETCH_USER_BATCH_SUCCESS = 'FETCH_USER_BATCH_SUCCESS';

export const FETCH_TWEET_STARTED = 'FETCH_TWEET_STARTED';
export const FETCH_TWEET_FAILURE = 'FETCH_TWEET_FAILURE';
export const FETCH_TWEET_SUCCESS = 'FETCH_TWEEET_SUCCESS';

export const FETCH_EVENT_BY_NAME_STARTED = 'FETCH_EVENT_BY_NAME_STARTED';
export const FETCH_EVENT_BY_NAME_FAILURE = 'FETCH_EVENT_BY_NAME_FAILURE';
export const FETCH_EVENT_BY_NAME_SUCCESS = 'FETCH_EVENT_BY_NAME_SUCCESS';
export const FETCH_PROG_DATA_BY_NAME_STARTED = 'FETCH_PROG_DATA_BY_NAME_STARTED';
export const FETCH_PROG_DATA_BY_NAME_FAILURE = 'FETCH_PROG_DATA_BY_NAME_FAILURE';
export const FETCH_PROG_DATA_BY_NAME_SUCCESS = 'FETCH_PROG_DATA_BY_NAME_SUCCESS';
export const FETCH_DIFFUSION_DATA_STARTED = 'FETCH_DIFFUSION_DATA_STARTED';
export const FETCH_DIFFUSION_DATA_FAILURE = 'FETCH_DIFFUSION_DATA_FAILURE';
export const FETCH_DIFFUSION_DATA_SUCCESS = 'FETCH_DIFFUSION_DATA_SUCCESS';
export const FETCH_DIFFUSION_IDS_STARTED = 'FETCH_DIFFUSION_IDS_STARTED';
export const FETCH_DIFFUSION_IDS_FAILURE = 'FETCH_DIFFUSION_IDS_FAILURE';
export const FETCH_DIFFUSION_IDS_SUCCESS = 'FETCH_DIFFUSION_IDS_SUCCESS';
export const FETCH_URL_PREVIEW_STARTED = 'FETCH_URL_PREVIEW_STARTED';
export const FETCH_URL_PREVIEW_FAILURE = 'FETCH_URL_PREVIEW_FAILURE';
export const FETCH_URL_PREVIEW_SUCCESS = 'FETCH_URL_PREVIEW_SUCCESS';

export const FETCH_OVERALL_TREND_STARTED = 'FETCH_OVERALL_TREND_STARTED';
export const FETCH_OVERALL_TREND_FAILURE = 'FETCH_OVERALL_TREND_FAILURE';
export const FETCH_OVERALL_TREND_SUCCESS = 'FETCH_OVERALL_TREND_SUCCESS';
