# build environment
FROM node:12 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app
COPY yarn.lock /app
RUN yarn install --frozen-lockfile
COPY . /app
RUN yarn build-prod

# production environment
FROM nginx:1.29.2-alpine-slim
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
